// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Runtime.InteropServices;
#pragma warning restore 0105

namespace My.Company
{
    public static partial class Interop
    {
        public const string NativeLib = "C:\\Users\\Administrator\\Desktop\\code_generator_rs\\target\\debug\\csharp_binding.dll";

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "create")]
        public static extern FFIError create(ref IntPtr context_ptr, string path);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "create_dto")]
        public static extern FFIError create_dto(IntPtr context_ptr);

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "dispose")]
        public static extern FFIError dispose(ref IntPtr context_ptr);

    }

    public enum FFIError
    {
        Ok = 0,
        NullPointerPassed = 10,
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error) : base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
